/**
 * Seed Product Catalog (real-world packaged foods with authentic UPC/EAN barcodes).
 * Health analysis is computed on demand by the rules engine for consistency.
 */

export const SEED_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Old Fashioned Whole Grain Rolled Oats',
    brand: 'Quaker Oats',
    barcode: '030000062002',
    category: 'Breakfast Grains',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '1/2 cup (40g)', servings_per_container: 30 },
      macros: {
        calories: { value: 150, unit: 'kcal' },
        total_fat: { value: 3, unit: 'g' },
        saturated_fat: { value: 0.5, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 0, unit: 'mg' },
        sodium: { value: 0, unit: 'mg' },
        total_carbohydrates: { value: 27, unit: 'g' },
        dietary_fiber: { value: 4, unit: 'g' },
        total_sugars: { value: 1, unit: 'g' },
        added_sugars: { value: 0, unit: 'g' },
        protein: { value: 5, unit: 'g' },
      },
      ingredients: ['100% Whole Grain Rolled Oats'],
      allergens_identified: [],
      product_name: 'Old Fashioned Whole Grain Rolled Oats',
      brand: 'Quaker Oats',
      barcode: '030000062002',
      category: 'Breakfast Grains',
    },
  },
  {
    id: 'prod-2',
    name: 'Hazelnut Spread with Cocoa',
    brand: 'Nutella',
    barcode: '3017620422003',
    category: 'Spreads & Sweeteners',
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '2 tbsp (37g)', servings_per_container: 10 },
      macros: {
        calories: { value: 200, unit: 'kcal' },
        total_fat: { value: 12, unit: 'g' },
        saturated_fat: { value: 4, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 0, unit: 'mg' },
        sodium: { value: 15, unit: 'mg' },
        total_carbohydrates: { value: 23, unit: 'g' },
        dietary_fiber: { value: 1, unit: 'g' },
        total_sugars: { value: 21, unit: 'g' },
        added_sugars: { value: 19, unit: 'g' },
        protein: { value: 2, unit: 'g' },
      },
      ingredients: [
        'Sugar',
        'Palm Oil',
        'Hazelnuts (13%)',
        'Skimmed Milk Powder (8.7%)',
        'Fat-Reduced Cocoa (7.4%)',
        'Soy Lecithin (Emulsifier)',
        'Vanillin (Artificial Flavor)',
      ],
      allergens_identified: ['Tree Nuts', 'Milk / Dairy', 'Soybeans / Soy'],
      product_name: 'Hazelnut Spread with Cocoa',
      brand: 'Nutella',
      barcode: '3017620422003',
      category: 'Spreads & Sweeteners',
    },
  },
  {
    id: 'prod-3',
    name: 'Total 0% Plain Nonfat Greek Yogurt',
    brand: 'FAGE',
    barcode: '041500000251',
    category: 'Dairy & Yogurt',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '3/4 cup (170g)', servings_per_container: 1 },
      macros: {
        calories: { value: 90, unit: 'kcal' },
        total_fat: { value: 0, unit: 'g' },
        saturated_fat: { value: 0, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 10, unit: 'mg' },
        sodium: { value: 65, unit: 'mg' },
        total_carbohydrates: { value: 5, unit: 'g' },
        dietary_fiber: { value: 0, unit: 'g' },
        total_sugars: { value: 5, unit: 'g' },
        added_sugars: { value: 0, unit: 'g' },
        protein: { value: 18, unit: 'g' },
      },
      ingredients: [
        'Grade A Pasteurized Skimmed Milk',
        'Live Active Yogurt Cultures (L. Bulgaricus, S. Thermophilus, L. Acidophilus, Bifidus, L. Casei)',
      ],
      allergens_identified: ['Milk / Dairy'],
      product_name: 'Total 0% Plain Nonfat Greek Yogurt',
      brand: 'FAGE',
      barcode: '041500000251',
      category: 'Dairy & Yogurt',
    },
  },
  {
    id: 'prod-4',
    name: 'Original Chocolate Sandwich Cookies',
    brand: 'Oreo',
    barcode: '044000032029',
    category: 'Snack Foods',
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '3 cookies (34g)', servings_per_container: 12 },
      macros: {
        calories: { value: 160, unit: 'kcal' },
        total_fat: { value: 7, unit: 'g' },
        saturated_fat: { value: 2, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 0, unit: 'mg' },
        sodium: { value: 135, unit: 'mg' },
        total_carbohydrates: { value: 25, unit: 'g' },
        dietary_fiber: { value: 1, unit: 'g' },
        total_sugars: { value: 14, unit: 'g' },
        added_sugars: { value: 14, unit: 'g' },
        protein: { value: 1, unit: 'g' },
      },
      ingredients: [
        'Unbleached Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid)',
        'Sugar',
        'Palm and/or Canola Oil',
        'Cocoa (Processed with Alkali)',
        'High Fructose Corn Syrup',
        'Leavening (Baking Soda and/or Calcium Phosphate)',
        'Salt',
        'Soy Lecithin',
        'Chocolate',
        'Artificial Flavor',
      ],
      allergens_identified: ['Gluten / Wheat', 'Soybeans / Soy'],
      product_name: 'Original Chocolate Sandwich Cookies',
      brand: 'Oreo',
      barcode: '044000032029',
      category: 'Snack Foods',
    },
  },
  {
    id: 'prod-5',
    name: 'Nacho Cheese Flavored Tortilla Chips',
    brand: 'Doritos',
    barcode: '028400090896',
    category: 'Snack Foods',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '12 chips (28g)', servings_per_container: 9 },
      macros: {
        calories: { value: 150, unit: 'kcal' },
        total_fat: { value: 8, unit: 'g' },
        saturated_fat: { value: 1, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 0, unit: 'mg' },
        sodium: { value: 210, unit: 'mg' },
        total_carbohydrates: { value: 18, unit: 'g' },
        dietary_fiber: { value: 1, unit: 'g' },
        total_sugars: { value: 1, unit: 'g' },
        added_sugars: { value: 0, unit: 'g' },
        protein: { value: 2, unit: 'g' },
      },
      ingredients: [
        'Corn',
        'Vegetable Oil (Corn, Canola, and/or Sunflower Oil)',
        'Maltodextrin',
        'Salt',
        'Cheddar Cheese (Milk, Cheese Cultures, Salt, Enzymes)',
        'Whey',
        'Monosodium Glutamate (MSG)',
        'Yellow 6',
        'Yellow 5',
        'Red 40',
        'Artificial Flavor',
      ],
      allergens_identified: ['Milk / Dairy'],
      product_name: 'Nacho Cheese Flavored Tortilla Chips',
      brand: 'Doritos',
      barcode: '028400090896',
      category: 'Snack Foods',
    },
  },
  {
    id: 'prod-6',
    name: 'Unsweetened Almond Milk',
    brand: 'California Almond',
    barcode: '085239045610',
    category: 'Plant Milk',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '1 cup (240ml)', servings_per_container: 8 },
      macros: {
        calories: { value: 30, unit: 'kcal' },
        total_fat: { value: 2.5, unit: 'g' },
        saturated_fat: { value: 0, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 0, unit: 'mg' },
        sodium: { value: 170, unit: 'mg' },
        total_carbohydrates: { value: 1, unit: 'g' },
        dietary_fiber: { value: 1, unit: 'g' },
        total_sugars: { value: 0, unit: 'g' },
        added_sugars: { value: 0, unit: 'g' },
        protein: { value: 1, unit: 'g' },
      },
      ingredients: ['Almondmilk (Filtered Water, Almonds)', 'Calcium Carbonate', 'Sea Salt', 'Gellan Gum', 'Sunflower Lecithin', 'Vitamin E Acetate', 'Vitamin A Palmitate', 'Vitamin D2'],
      allergens_identified: ['Tree Nuts'],
      product_name: 'Unsweetened Almond Milk',
      brand: 'California Almond',
      barcode: '085239045610',
      category: 'Plant Milk',
    },
  },
  {
    id: 'prod-7',
    name: 'Dark Chocolate Nuts & Sea Salt Bar',
    brand: 'KIND',
    barcode: '602652171015',
    category: 'Snack Foods',
    imageUrl: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '1 bar (40g)', servings_per_container: 1 },
      macros: {
        calories: { value: 200, unit: 'kcal' },
        total_fat: { value: 15, unit: 'g' },
        saturated_fat: { value: 3.5, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 0, unit: 'mg' },
        sodium: { value: 140, unit: 'mg' },
        total_carbohydrates: { value: 16, unit: 'g' },
        dietary_fiber: { value: 7, unit: 'g' },
        total_sugars: { value: 5, unit: 'g' },
        added_sugars: { value: 4, unit: 'g' },
        protein: { value: 6, unit: 'g' },
      },
      ingredients: [
        'Almonds',
        'Peanuts',
        'Dark Chocolate Coating (Sugar, Palm Kernel Oil, Cocoa Powder, Soy Lecithin, Natural Flavor, Salt)',
        'Chicory Root Fiber',
        'Honey',
        'Glucose Syrup',
        'Rice Flour',
        'Sea Salt',
        'Soy Lecithin',
      ],
      allergens_identified: ['Tree Nuts', 'Peanuts', 'Soybeans / Soy'],
      product_name: 'Dark Chocolate Nuts & Sea Salt Bar',
      brand: 'KIND',
      barcode: '602652171015',
      category: 'Snack Foods',
    },
  },
  {
    id: 'prod-8',
    name: 'Classic Potato Chips',
    brand: 'Lay\'s',
    barcode: '028400000031',
    category: 'Snack Foods',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop',
    isCommunity: false,
    analysis: {
      serving_info: { serving_size: '15 chips (28g)', servings_per_container: 8 },
      macros: {
        calories: { value: 160, unit: 'kcal' },
        total_fat: { value: 10, unit: 'g' },
        saturated_fat: { value: 1.5, unit: 'g' },
        trans_fat: { value: 0, unit: 'g' },
        cholesterol: { value: 0, unit: 'mg' },
        sodium: { value: 170, unit: 'mg' },
        total_carbohydrates: { value: 15, unit: 'g' },
        dietary_fiber: { value: 1, unit: 'g' },
        total_sugars: { value: 0, unit: 'g' },
        added_sugars: { value: 0, unit: 'g' },
        protein: { value: 2, unit: 'g' },
      },
      ingredients: ['Potatoes', 'Vegetable Oil (Canola, Corn, Soybean, and/or Sunflower Oil)', 'Salt'],
      allergens_identified: [],
      product_name: 'Classic Potato Chips',
      brand: 'Lay\'s',
      barcode: '028400000031',
      category: 'Snack Foods',
    },
  },
];
